language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - phpenv config-add travis.php.ini
  - composer install --no-interaction
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn encore production

after_failure:
  - cat /home/travis/build/SURFnet/sp-dashboard/var/logs/test.log

script:
  - ant

branches:
  only:
    - develop
    - master