language: php

php:
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - ~/.composer/cache/files

before_script:
  - echo 'date.timezone = "Europe/Amsterdam"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install --no-interaction

script:
  - ant

branches:
  only:
    - master