---
- name: Import the mongo CA file
  copy:
    src: "{{ inventory_dir }}/files/certs/mongo/{{ mongo_tls_ca }}"
    dest: "{{ tls.cert_path_ca }}/"
  when:
    - mongo_tls

- name: Update the ca trust store
  command: /bin/update-ca-trust
  changed_when: False

- name: Create manage-prd dir
  file:
    path: "{{ manage_dir }}"
    state: directory
    owner: manage
    group: manage
    mode: 0775

- name: Copy systemd service file
  template:
    src: "../../../OpenConext-deploy/templates/spring-boot.service.j2"
    dest: "/etc/systemd/system/{{ springapp_service_name }}.service"
  notify:
    - "systemctl daemon-reload"
    - "restart manage-prd"

- name: enable service
  service:
    name: manage-prd
    enabled: yes

- name: Create logging directory
  file:
    path: "/var/log/{{ springapp_service_name }}"
    state: directory
    owner: manage
    group: manage
    mode: 0755

- name: Create mongo database users
  mongodb_user:
    login_database: admin
    database: "{{ mongo.manage_database_prod }}" 
    login_user: admin
    login_password: "{{ mongo_admin_pass }}" 
    name: "{{ mongo.manage_prod_user }}" 
    password: "{{ mongo.manage_password }}" 
    roles: readWrite
    replica_set: "{{ replica_set_name }}" 

- name: Include install-maven-release.yml
  include: ../../../OpenConext-deploy/tasks/springbootapp/install-maven-release.yml
  when:
    - "manage_local_jar == ''"

- name: Include install-local.yml
  include: ../../../OpenConext-deploy/tasks/springbootapp/install-local.yml
  when:
    - "manage_local_jar != ''"

- name: copy logging config
  template:
    src: "logback.xml.j2"
    dest: "{{ manage_dir }}/logback.xml"
    owner: manage
    group: manage
    mode: 0740
  notify:
    - "restart manage-prd"

- name: copy application config
  template:
    src: "application.yml.j2"
    dest: "{{ manage_dir }}/application.yml"
    owner: manage
    group: manage
    mode: 0740
  notify:
    - "restart manage-prd"

- name: copy api users
  template:
    src: "manage-api-users.yml.j2"
    dest: "{{ manage_dir }}/manage-api-users.yml"
    owner: manage
    group: manage
    mode: 0740
  notify:
    - "restart manage-prd"

- name: Create metadata configuration directory
  file:
    path: "{{ manage_dir }}/metadata_configuration"
    state: directory
    owner: manage
    group: manage
    mode: 0740

- name: copy metadata configuration
  copy:
    src: "metadata_configuration"
    dest: "{{ manage_dir }}"
    owner: manage
    group: manage
    mode: 0640
  tags: deploy
  notify:
    - "restart manage-prd"

- name: Create metadata export directory
  file:
    path: "{{ manage_dir }}/metadata_export"
    state: directory
    owner: manage
    group: manage
    mode: 0740

- name: copy metadata export
  copy:
    src: metadata_export
    dest: "{{ manage_dir }}"
    owner: manage
    group: manage
    mode: 0640
  tags:
    - deploy
  notify:
    - "restart manage-prd"

- name: Create metadata templates directory
  file:
    path: "{{ manage_dir }}/metadata_templates"
    state: directory
    owner: manage
    group: manage
    mode: 0740

- name: copy metadata templates
  copy:
    src: "metadata_templates"
    dest: "{{ manage_dir }}"
    owner: manage
    group: manage
    mode: 0640
  tags:
    - deploy
  notify:
    - "restart manage-prd"

- name: start the manage service
  service:
    name: manage-prd
    state: started
    enabled: yes
  ignore_errors: true

- name: wait for manage to start
  wait_for:
    connect_timeout: 30
    port: "{{ springapp_tcpport }}"
    state: started

- name: ensure the service is started
  service:
    name: manage-prd
    enabled: yes
    state: started

- name: cleanup old jars
  shell: find . ! -name $(basename $(readlink manage-current.jar)) -name '*.jar' -type f -exec rm {} \; chdir={{ manage_dir }}
  when: maven_result.changed
