imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.root_dir%/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
        save_path: '/tmp/sp-dashboard-sessions'

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    port: 1025
