---
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes

- name: restart manage-prd
  service:
    name: manage-prd
    state: restarted

- name: update_ca_trust
  command: update-ca-trust
