---
- name: Install necessary packages for installing Mailcatcher
  yum: pkg={{ item }} state=present
  with_items:
    - ruby-devel
    - gcc-c++
    - sqlite-devel

- name: Install Mailcatcher
  action: command gem install mailcatcher creates=/usr/local/bin/mailcatcher